kind: PersistentVolume
apiVersion: v1
metadata:
  name: fabric-pv
  labels: 
    type: local
    name: fabricfiles
spec: 
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /nfs/fabric