#apiVersion: extensions/v1beta1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer
spec:
  selector:
    matchLabels:
      name: orderer
  replicas: 1
  template:
    metadata:
      labels:
        name: orderer
    spec:
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: fabric-pvc
      
      containers:
        - name: orderer
          image: hyperledger/fabric-orderer:2.2.1
          command: ["sh","-c","orderer"]
          env:
            - name: ORDERER_CFG_PATH
              value: /fabric/
            - name: CONFIGTX_ORDERER_ADDRESSES
              value: "orderer1.grainchain.io:7050"
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: 0.0.0.0
            - name: ORDERER_GENERAL_LISTENPORT
              value: "7050"
            - name: ORDERER_GENERAL_LOGLEVEL
              value: debug
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: /fabric/ca/client/ordererOrganizations/orderers/orderers/orderer1.grainchain.io/msp
            - name: ORDERER_GENERAL_LOCALMSPID
              value: orderersMSP
            - name: ORDERER_GENERAL_GENESISMETHOD
              value: file
            - name: ORDERER_GENERAL_GENESISFILE
              value: /fabric/genesis.block
            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "true"
            - name: ORDERER_GENERAL_TLS_PRIVATEKEY
              value: /fabric/ca/client/ordererOrganizations/orderers/orderers/orderer1.grainchain.io/tls-msp/keystore/key.pem
            - name: ORDERER_GENERAL_TLS_CERTIFICATE
              value: /fabric/ca/client/ordererOrganizations/orderers/orderers/orderer1.grainchain.io/tls-msp/signcerts/cert.pem
            - name: ORDERER_GENERAL_TLS_ROOTCAS
              value: /fabric/ca/client/ordererOrganizations/orderers/orderers/orderer1.grainchain.io/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem
            - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
              value: /fabric/ca/client/ordererOrganizations/orderers/orderers/orderer1.grainchain.io/tls-msp/keystore/key.pem
            - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
              value: /fabric/ca/client/ordererOrganizations/orderers/orderers/orderer1.grainchain.io/tls-msp/signcerts/cert.pem
          volumeMounts:
            - mountPath: /fabric
              name: fabricfiles
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "orderer1.grainchain.io"
        - ip: "10.103.126.196"
          hostnames:
          - "orderer1.grainchain.io"
        - ip: "10.98.16.245"
          hostnames:
          - "orderer2.grainchain.io"
        - ip: "10.104.13.223"
          hostnames:
          - "orderer3.grainchain.io"
        - ip: "10.96.135.161"
          hostnames:
          - "orderer4.grainchain.io"
        - ip: "10.103.239.242"
          hostnames:
          - "orderer5.grainchain.io"
        - ip: "10.108.231.224"
          hostnames:
          - "peer1-harvx.grainchain.io"
        - ip: "10.105.199.58"
          hostnames:
          - "peer2-harvx.grainchain.io"
        - ip: "10.111.125.78"
          hostnames:
          - "peer1-commodity.grainchain.io"
        - ip: "10.109.167.154"
          hostnames:
          - "peer2-commodity.grainchain.io"