apiVersion: v1
kind: Service
metadata:
  name: harvxpeer0
  labels:
    run: harvxpeer0
spec: 
  type: ClusterIP
  selector:
    name: harvxpeer0
  ports:
    - protocol: TCP
      port: 7051
      name: grpc
    - protocol: TCP
      port: 7052
      name: chaincode
    - protocol: TCP
      port: 7061
      name: events
    - protocol: TCP
      port: 5984
      name: couchdb