apiVersion: apps/v1
kind: Deployment
metadata: 
  name: harvxpeer1
spec:
  selector:
    matchLabels:
      name: harvxpeer1
  replicas: 1
  template:
    metadata:
      labels:
        name: harvxpeer1
    spec:
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: fabric-pvc
        - name: runfiles
          persistentVolumeClaim:
            claimName: run-pvc
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock
      containers:
      - name: peer
        image: hyperledger/fabric-peer:2.2.1
        command: ["sh", "-c", "peer node start"]
        env:
        - name: FABRIC_CFG_PATH
          value: /fabric/config
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "false"
        - name: CORE_PEER_ID
          value: peer2-harvx.grainchain.io
        - name: CORE_PEER_ADDRESS
          value: peer2-harvx.grainchain.io:7051
        - name: CORE_PEER_LISTENADDRESS
          value: "0.0.0.0:7051"
        - name: CORE_PEER_EVENTS_ADDRESS
          value: "0.0.0.0:7061"
        - name: CORE_PEER_CHAINCODEADDRESS
          value: "peer2-harvx.grainchain.io:7052"
        - name: CORE_PEER_CHAINCODELISTENADDRESS
          value: "0.0.0.0:7052"
        - name: CORE_PER_GOSSIP_BOOTSTRAP
          value: peer1-harvx.grainchain.io:7051
        - name: CORE_PEER_GOSSIP_ENDPOINT
          value: peer2-harvx.grainchain.io:7051
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: peer2-harvx.grainchain.io:7051
        - name: CORE_PEER_GOSSIP_OGRLEADER
          value: "false"
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "false"
        - name: CORE_PEER_PROFILE_ENABLED
          value: "false"
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_PEER_LOCALMSPID
          value: harvxMSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /fabric/ca/client/peerOrganizations/harvx/peers/peer2-harvx.grainchain.io/msp/
        - name: FABRIC_LOGGIN_SPEC
          value: debug
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: /fabric/ca/client/peerOrganizations/harvx/peers/peer2-harvx.grainchain.io/tls-msp/signcerts/cert.pem
        - name: CORE_PEER_TLS_KEY_FILE
          value: /fabric/ca/client/peerOrganizations/harvx/peers/peer2-harvx.grainchain.io/tls-msp/keystore/key.pem
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /fabric/ca/client/peerOrganizations/harvx/peers/peer2-harvx.grainchain.io/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: "CouchDB"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: "localhost:5984"
        - name: FABRIC_CONFIG_PATH
          value: /etc/hyperledger/fabric/
        - name: ORDERER_URL
          value: orderer:7050
        - name: ORDERER_URL
          value: orderer2:7050
        - name: ORDERER_URL
          value: orderer3:7050
        - name: ORDERER_URL
          value: orderer4:7050
        - name: ORDERER_URL
          value: orderer5:7050
        volumeMounts:
          - mountPath: /fabric
            name: fabricfiles
          - mountPath: /host/var/run/docker.sock
            name: dockersocket
          - mountPath: /var/run
            name: runfiles
      - name: couchdb
        image: hyperledger/fabric-couchdb:0.4.21
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "peer2-harvx.grainchain.io"

        - ip: "10.103.126.196"
          hostnames:
          - "orderer1.grainchain.io"
        - ip: "10.98.16.245"
          hostnames:
          - "orderer2.grainchain.io"
        - ip: "10.104.13.223"
          hostnames:
          - "orderer3.grainchain.io"
        - ip: "10.96.135.161"
          hostnames:
          - "orderer4.grainchain.io"
        - ip: "10.103.239.242"
          hostnames:
          - "orderer5.grainchain.io"
        - ip: "10.108.231.224"
          hostnames:
          - "peer1-harvx.grainchain.io"
        - ip: "10.105.199.58"
          hostnames:
          - "peer2-harvx.grainchain.io"
        - ip: "10.111.125.78"
          hostnames:
          - "peer1-commodity.grainchain.io"
        - ip: "10.109.167.154"
          hostnames:
          - "peer2-commodity.grainchain.io"