apiVersion: v1
kind: Service
metadata:
  name: tools
  labels:
    run: tooles
spec: 
  type: ClusterIP
  selector:
    name: tools
  ports:
    - protocol: TCP
      port: 7051
      name: grpc
    - protocol: TCP
      port: 7052
      name: chaincode
    - protocol: TCP
      port: 7061
      name: events
    - protocol: TCP
      port: 5984
      name: couchdb