apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tools
spec:
  selector:
    matchLabels:
      name: tools
  replicas: 1
  template:
    metadata:
      labels:
        name: tools
    spec:
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: fabric-pvc
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock
      containers:
      - name: peer
        image: hyperledger/fabric-tools:2.2.1
        command: ["sh","-c","sleep 48h"]
        env:
        - name: CORE_PEER_ID
          value: peer1-harvx.grainchain.io
        - name: CORE_PEER_ADDRESS
          value: peer1-harvx.grainchain.io:7051
        - name: CORE_VM_ENDPONT
          value: unix:///host/var/run/docker.sock
        - name: CORE_PEER_LOCALMSPID
          value: harvxMSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /fabric/ca/client/peerOrganizations/harvx/users/admin/msp
        - name: FABRIC_LOGGIN_SPEC
          value: debug
        - name: FABRIC_CONFIG_PATH
          value: /etc/hyperledger/fabric/
        
        volumeMounts:
          - mountPath: /fabric
            name: fabricfiles
          - mountPath: /host/var/run/docker.sock
            name: dockersocket
      hostAliases:
        - ip: "10.103.126.196"
          hostnames:
          - "orderer1.grainchain.io"
        - ip: "10.98.16.245"
          hostnames:
          - "orderer2.grainchain.io"
        - ip: "10.104.13.223"
          hostnames:
          - "orderer3.grainchain.io"
        - ip: "10.96.135.161"
          hostnames:
          - "orderer4.grainchain.io"
        - ip: "10.103.239.242"
          hostnames:
          - "orderer5.grainchain.io"
        - ip: "10.108.231.224"
          hostnames:
          - "peer1-harvx.grainchain.io"
        - ip: "10.105.199.58"
          hostnames:
          - "peer2-harvx.grainchain.io"
        - ip: "10.111.125.78"
          hostnames:
          - "peer1-commodity.grainchain.io"
        - ip: "10.109.167.154"
          hostnames:
          - "peer2-commodity.grainchain.io"